<?php
// ------ configurações do gráfico ----------
$titulo = "Torcedores do Rio Grande do Sul";
$largura = 700;
$altura = 400;
$largura_eixo_x = 450;
$largura_eixo_y = 300;
$inicio_grafico_x = 70;
$inicio_grafico_y = 360;

// ------ configurações da legenda ----------
$exibir_legenda = "sim";
$fonte = 3;
$largura_fonte = 8; // largura em pixels (2=6,3=8,4=10)
$altura_fonte = 10; // altura em pixels (2=8,3=10,4=12)
$espaco_entre_linhas = 10;
$margem_vertical = 5;

// canto superior direito da legenda
$lx = 660;
$ly = 30;
?>
