<?php
// Configurações do servidor FTP
$servidor_ftp = "192.168.1.36";
$usario_ftp = "julianoz";
$senha_ftp = "12345";

// Limitar as extensões? (sim ou nao)
$limitar_ext = "sim";

// extensões autorizadas
$extensoes_validas = array(".gif",".jpg",".jpeg",".bmp");

//caminho absoluto onde os arquivos serão armazenados
$caminho_absoluto = "public_html/upload";

// Limitar o tamanho do arquivo? (sim ou nao)
$limitar_tamanho = "nao";

// tamanho limite do arquivo em bytes
$tamanho_bytes = "2000000";

// se já existir o arquivo, indica se ele deve ser sobrescrito (sim ou nao)
$sobrescrever = "nao";

?>
